ALTER TABLE IF EXISTS "BookingItem"
ADD COLUMN IF NOT EXISTS "resourceTitle" TEXT,
ADD COLUMN IF NOT EXISTS "priceType" "ItemPriceType",
ADD COLUMN IF NOT EXISTS "basePriceCents" INTEGER,
ADD COLUMN IF NOT EXISTS "priceLabel" TEXT,
ADD COLUMN IF NOT EXISTS "displayPrice" TEXT,
ADD COLUMN IF NOT EXISTS "pricingMode" TEXT,
ADD COLUMN IF NOT EXISTS "pricingReason" TEXT,
ADD COLUMN IF NOT EXISTS "bookingDays" INTEGER,
ADD COLUMN IF NOT EXISTS "calculatedUnitPriceCents" INTEGER,
ADD COLUMN IF NOT EXISTS "calculatedTotalPriceCents" INTEGER;
